# Generated by Django 4.2.19 on 2025-04-13 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glacier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('image', models.ImageField(upload_to='glacier_images/')),
                ('description', models.TextField()),
                ('event_type', models.CharField(max_length=100)),
                ('outburst_mechanism', models.TextField()),
                ('area_map', models.ImageField(upload_to='area_maps/')),
                ('area_description', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('risk_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
